### ISSUE TITLE
Do not move

### ISSUE THREAD

**Issue by ogata2606** [uber-common/deep-neuroevolution#5]
Thank you for opening code.
Along with your Readme.md, I did

` . scripts/local_run_redis.sh `

error happens 

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 80
>>> 'protected-mode yes'
Bad directive or wrong number of arguments

What is protected-mode? and what should I do to do program?

**Comment by eavelardev** [comment]
you need install the latest version of redis server
https://redis.io/topics/quickstart

**Comment by VashishtMadhavan** [comment]
@eavelardev is correct this is a redis-server issue
