### ISSUE TITLE
Data format for dimensionality reduction [Atari domain]

### ISSUE THREAD

**Issue by RihabGor** [uber-common/deep-neuroevolution#9]
Hello, 
To be able to visualize the cloud plot using vine for the Atari domain, you said that we need to capture the final emulator RAM state ( integer-valued vectors of length 128 that capture all the state variables in a game) as the BC, I am wondering what format of data should we be entering as input to the "process_bc" script for dimensionality reduction ?
Thank you!

**Comment by ruiwang2uber** [comment]
Hello @RihabGor ,

Thanks for your interest in VINE.

es_modified.py is an example where you need to save the data for VINE.

https://github.com/uber-common/deep-neuroevolution/blob/master/es_distributed/es_modified.py#L179 

The basic format is: each row for one of the psuedo-offspings
[RAM, fitness, length, noise_idx, policy_seed, sign] 

To prepare data for VINE:
When training, please replace es.py with es_modified.py

Then automatically all the data  (final RAM state) is saved for you and can directly consumed by VINE.
